version: '3.8'
services:
  influxdb:
    image: influxdb:2.7
    container_name: smart_defect_db
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=testops_org
      - DOCKER_INFLUXDB_INIT_BUCKET=observability_bucket

  grafana:
    image: grafana/grafana:latest
    container_name: smart_defect_dashboard
    ports:
      - "3000:3000"
    depends_on:
      - influxdb